import chalk from"chalk";import puppeteer from"puppeteer";import evaluateImage from"./utils/evaluateImage.js";import logQrcode from"./utils/logQrcode.js";import waitForFunctionImage from"./utils/waitForFunctionImage.js";import onPageLog from"./utils/onPageLog.js";import sendMsg from"./utils/sendMsg.js";export default async function wxappPublish(){var{puppeteerLunchOptions:e,pageDebug:o,timeout:t}=global.__wxapp_publish_config__||{};e=await puppeteer.launch(e||{headless:!0});var n=await e.newPage();n.setDefaultTimeout(t||1e5),await n.goto("https://mp.weixin.qq.com/"),o&&onPageLog(n),console.log(chalk.green("获取登录二维码")),await n.waitForSelector("img"),await n.waitForFunction(()=>{var e=document.querySelector(".login__type__container__scan__qrcode");return!(!e||!e.getAttribute("src"))});t=await evaluateImage(n,".login__type__container__scan__qrcode");try{await logQrcode(t)}catch(e){console.log(chalk.red(e))}console.log(chalk.green("请扫码登录")),await n.waitForFunction(()=>{return!![...document.querySelectorAll(".menu_item")].filter(e=>"版本管理"===e.querySelector("a").innerText.trim())[0]});o=await n.evaluate(()=>window.__INITIAL_STATE__.userInfo);t=o.login_user;var r=t.is_admin?"管理员、":"";r=(r=(r=(r+=t.is_operator?"运营者、":"")+(t.is_developer?"开发者、":""))+(t.is_data?"数据分析者、":""))+(t.is_experience?"体验成员":""),console.log(chalk.green("MP后台登录成功")),console.log(chalk.green("小程序Appid：",o.appid)),console.log(chalk.green("小程序名称：",o.nickName)),console.log(chalk.green("登录角色：",r)),sendMsg({msgtype:"markdown",markdown:{content:`<font color="info">登录成功</font>, 登录小程序信息：

         >小程序名称：<font color="comment">${o.nickName}</font>
         >小程序Appid：<font color="comment">${o.appid}</font>
         >登录者角色：<font color="comment">${r}</font>`}});t=await n.evaluateHandle(()=>{return[...document.querySelectorAll(".menu_item")].filter(e=>"版本管理"===e.querySelector("a").innerText.trim())[0]});t&&t.click(),console.log(chalk.green("跳转【版本管理】")),await n.waitForFunction(()=>{return!![...document.querySelectorAll(".mod_default_hd.test_version")].filter(e=>"审核版本"===e.querySelector("h4").innerText.trim())[0]});o=await n.evaluate(()=>{var e=document.querySelector(".mod_default_bd.default_box.test_version .code_version_log_hd .simple_preview_item .status_tag");return e?e.innerText.trim():""});if(o)if(r=await n.evaluate(()=>{var e=".mod_default_bd.default_box.test_version .default_box_inner ";return{vision:document.querySelector(e+" .code_version_log_hd .simple_preview_value").innerText.trim(),developer:document.querySelector(e+" .code_version_log_bd .simple_preview_item:first-child .simple_preview_value").innerText.trim(),pushTime:document.querySelectorAll(e+" .code_version_log_bd .simple_preview_item")[1].querySelector(".simple_preview_value").innerText.trim(),desc:document.querySelector(e+" .code_version_log_bd .simple_preview_item:last-child .simple_preview_value").innerText.trim()}}),console.log(chalk.green("审核状态：",o)),console.log(chalk.green("版本号：",r.vision)),console.log(chalk.green("开发者：",r.developer)),sendMsg({msgtype:"markdown",markdown:{content:`<font color="info">已检测到待发布小程序</font>，版本信息：

            >审核状态：<font color="comment">${o}</font>
            >版本号：<font color="comment">${r.vision}</font>
            >开发者：<font color="comment">${r.developer}</font>
            >提交审核时间：<font color="comment">${r.pushTime}</font>
            >项目备注：<font color="comment">${r.desc}</font>`}}),"审核中"===o)console.log(chalk.red("版本审核中")),sendMsg({msgtype:"text",text:{content:"当前版本审核中, 发版结束"}});else{t=await n.evaluate(()=>{return document.querySelector(".code_version_log_hd .weui-desktop-popover_pos-up-left .weui-desktop-popover__desc").innerText.trim()});if("审核不通过"===o)console.log(chalk.red("审核结果：【审核不通过】")),console.log(chalk.red("不通过原因：",t+"https://mp.weixin.qq.com/wxamp/wadevelopcode/get_class?action=get_class&openid=oMf5b5U-X1WHoVenpkf4ngfSTTbw&user_name=WGinit&audit_id=431196256&token=710610173&lang=zh_CN")),sendMsg({msgtype:"markdown",markdown:{content:`<font color="warning">${o}</font>, 登录信息：

             >原因：<font color="comment">${t}https://mp.weixin.qq.com/wxamp/wadevelopcode/get_class?action=get_class&openid=oMf5b5U-X1WHoVenpkf4ngfSTTbw&user_name=WGinit&audit_id=431196256&token=710610173&lang=zh_CN</font>`}});else{console.log(chalk.green("检测到可发布版本"));r=await n.evaluateHandle(()=>{var e=document.querySelectorAll(".code_version_test .code_version_log_ft .weui-desktop-btn");return e?[...e].filter(e=>"提交发布"===e.innerText.trim())[0]:null});r&&(console.log("点击按钮"),r.click()),await n.waitForFunction(()=>{var e=document.querySelectorAll(".weui-desktop-dialog .weui-desktop-dialog__hd .weui-desktop-dialog__title");let o=null;return!!(o=e?[...e].filter(e=>"发布线上版本"===e.innerText.trim())[0]:o)});t=await n.evaluateHandle(()=>{var e=document.querySelectorAll(".weui-desktop-dialog .weui-desktop-dialog__hd .weui-desktop-dialog__title");let o=null;return[...(o=e?[...e].filter(e=>"发布线上版本"===e.innerText.trim())[0]:o)?o.parentElement.parentElement.querySelectorAll(".weui-desktop-dialog__ft .weui-desktop-btn_wrp .weui-desktop-btn_primary"):[]].filter(e=>"提交"===e.innerText.trim())[0]});t&&(console.log(chalk.green("点击提交按钮")),t.click());await n.waitForFunction(()=>{var e=document.querySelector(".weui-desktop-dialog__bd .dialog_bd .weui-desktop-qrcheck .weui-desktop-qrcheck__qrcode-area .weui-desktop-qrcheck__img");return!(!e||!e.getAttribute("src"))});r=await evaluateImage(n,".weui-desktop-dialog__bd .dialog_bd .weui-desktop-qrcheck .weui-desktop-qrcheck__qrcode-area .weui-desktop-qrcheck__img");try{await logQrcode(r,"publish")}catch(e){console.log(chalk.red(e))}console.log(chalk.green("请扫码发布")),await n.waitForFunction(()=>{return!document.querySelector(".mod_default_bd.default_box.test_version .code_version_log_hd .simple_preview_item .status_tag")}),console.log(chalk.green("发布成功")),sendMsg({msgtype:"markdown",markdown:{content:'<font color="info">发布成功！</font>发版结束。'}})}}else console.log(chalk.red("当前暂无审核版本")),sendMsg({msgtype:"text",text:{content:o||"当前暂无审核版本, 发版结束"}});await e.close()}